// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAipNe_NktkvNBkSbXHLrtMzaIM5J16wZQ',
    appId: '1:1002557691776:web:3f0cd9d2c607bfc9491365',
    messagingSenderId: '1002557691776',
    projectId: 'nexera-medibox',
    authDomain: 'nexera-medibox.firebaseapp.com',
    storageBucket: 'nexera-medibox.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB0kohcoiIXMdFKFnx3ynvWc2PUlqYbtQ',
    appId: '1:1002557691776:android:0445b38490b25d9c491365',
    messagingSenderId: '1002557691776',
    projectId: 'nexera-medibox',
    storageBucket: 'nexera-medibox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGW-_ApioNSrq-1lKZDYOJm_7abATpoOA',
    appId: '1:1002557691776:ios:3ad94a04e2e729cc491365',
    messagingSenderId: '1002557691776',
    projectId: 'nexera-medibox',
    storageBucket: 'nexera-medibox.firebasestorage.app',
    iosBundleId: 'com.example.nexeraMedibox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGW-_ApioNSrq-1lKZDYOJm_7abATpoOA',
    appId: '1:1002557691776:ios:3ad94a04e2e729cc491365',
    messagingSenderId: '1002557691776',
    projectId: 'nexera-medibox',
    storageBucket: 'nexera-medibox.firebasestorage.app',
    iosBundleId: 'com.example.nexeraMedibox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAipNe_NktkvNBkSbXHLrtMzaIM5J16wZQ',
    appId: '1:1002557691776:web:f8a3a8c08174bfac491365',
    messagingSenderId: '1002557691776',
    projectId: 'nexera-medibox',
    authDomain: 'nexera-medibox.firebaseapp.com',
    storageBucket: 'nexera-medibox.firebasestorage.app',
  );
}
